# Generated by Django 2.0.7 on 2020-04-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploads',
            new_name='upload',
        ),
    ]
