# Generated by Django 2.0.7 on 2020-04-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20200411_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='subject',
            field=models.CharField(choices=[('Business', 'Business'), ('Economics', 'Economics'), ('Commerce', 'Commerce'), ('Bangladesh_studies', 'Bangladesh Studies'), ('Accounting', 'Accounting'), ('Banking_Finance', 'Banking and Finance'), ('Business_Entrepreneurship', 'Business Entrepreneurship'), ('Geography', 'Geography'), ('Statistics', 'Statistics'), ('Language', 'Language')], max_length=25),
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
