# Generated by Django 2.0.7 on 2020-04-11 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20200411_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='upload',
            name='curriculum',
            field=models.CharField(choices=[('NC_BISE', 'NC (BISE)'), ('CIE', 'CIE'), ('Edexcel', 'Edexcel'), ('IB', 'IB')], max_length=25),
        ),
    ]
