# Generated by Django 2.0.7 on 2020-05-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogComment', '0003_delete_myblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog_id',
            field=models.IntegerField(),
        ),
    ]
