# Generated by Django 2.0.7 on 2020-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogComment', '0004_auto_20200506_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog_id',
            field=models.IntegerField(max_length=11),
        ),
    ]
