# Generated by Django 2.0.7 on 2020-05-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogComment', '0005_auto_20200509_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog_id',
            field=models.IntegerField(),
        ),
    ]
