# Generated by Django 2.0.7 on 2020-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='goals',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='summary',
            new_name='goals_description',
        ),
        migrations.AddField(
            model_name='about',
            name='goals_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mission_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='objective_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='objective_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
