# Generated by Django 2.0.7 on 2020-12-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='file',
        ),
    ]
