# Generated by Django 2.0.7 on 2020-05-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0004_auto_20200503_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myBlog_comments',
        ),
    ]
