# Generated by Django 2.0.7 on 2020-05-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlogs', '0008_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogComment',
        ),
    ]
